app:
  image: swift-08-30
  ports:
    - "8090:8090"
  volumes:
    - .:/root/watson-recommendations-api-kitura
  command: bash -c "make clean -C watson-recommendations-api-kitura && make -C watson-recommendations-api-kitura && watson-recommendations-api-kitura/.build/debug/restaurant-recommendations"
